### ISSUE TITLE
Refresh requires re-entry of seed phrase

### ISSUE THREAD

**Issue by clamoring** [MyHush/myhushwallet#12]
Expected behavior: Refreshing the page will update the addresses with recent transactions.

Actual behavior: Refreshing the page requires user to re-enter seed phrase.

**Comment by TheTrunk** [comment]
That is a wanted behaviour. That is why there is a button for refreshing. Reloading the page (like F5) would require storing the secret phrase. The wallet operates on user computer throught javascript, no server interaction - that is why it is secure.

**Comment by clamoring** [comment]
Makes sense. I think adding some wording explaining what is happening might be a better UX then.

**Comment by TheTrunk** [comment]
Yes the started page and some "white paper" is definitly needed!
