### ISSUE TITLE
Online Wallet Generator Creates Different Addresses From Local Wallet Generator

### ISSUE THREAD

**Issue by gaia** [MyHush/myhushwallet#17]
using the same passphrase, the online generator creates addresses beginning with a 't' while the locally run generator (current version) creates addresses beginning with a 'z'.

pls advise.

**Comment by Giuseppe0210** [comment]
I had my Hush coins on the previous wallet ,
now when i go to the new wallet and i open it with the old pass word that work my coin are not there anymore and i can see the address i use where i transfer my Hush coin from Cryptopia
My Hush address is

t1Wy939paXKo9stMVt5Y..........
