### ISSUE TITLE
access to my hush wallet

### ISSUE THREAD

**Issue by Giuseppe0210** [MyHush/myhushwallet#18]
I had my Hush coins on the previous wallet ,
now when i go to the new wallet and i open it with the old pass word that look like it  work my coin are not there anymore and i can't  see the address i used where i transfer my Hush coin from Cryptopia
My Hush address is

t1Wy939paXKo9stMVt5Y..........

in this wallet there are all new address 
I think is a new wallet 

how can i retrive my wallet and my coin 
i have my old address 

please help 

thank you

**Comment by TheTrunk** [comment]
The new wallet has the 64/256 button which is supposed to be clicked if your passphrase for the previous wallet was longer then 64 characters - in that case it was cut to just 64 characters. The new one supports up to 256 characters.
Eg. wallet phrase 70 characters -> old wallet takes the first 64 chars. New wallet takes the whole 70 chars.
