### ISSUE TITLE
Default example seed phrase too short

### ISSUE THREAD

**Issue by leto** [MyHush/myhushwallet#24]
Currently it shows a 9 word seed phrase, let's show 12 words instead, as a good example for users.

**Comment by gilardh** [comment]
Currently, the maximum size is 64 characters.
```
<Input
type={this.state.showPassword ? "text" : "password"}
maxLength="64"
onChange={(e) => this.setState({secretPhrase: e.target.value})}
placeholder="Secret phrase. e.g. hush puppy washington heros paris money bag time grey"
/> 
```

For exemple, the 12 words list below is 71 characters long and will be truncated:
'hush puppy washington heros paris money bag time grey seed good example'

**Comment by leto** [comment]
Ok, closing this
