### ISSUE TITLE
Still says "generate wallet" when typing in phrase to login

### ISSUE THREAD

**Issue by leto** [MyHush/myhushwallet#4]
![my hush wallet 2017-11-17 21-30-11](https://user-images.githubusercontent.com/30298/32977258-8c2beac4-cbde-11e7-9b74-ab135766c2fb.png)

Maybe we just have a button for "Login" versus "Generate" ?

I know why it's like it is, but I think it's confusing for end users.

**Comment by matthewjamesr** [comment]
How about **Generate Wallet / Login** or something to that nature @leto ?

**Comment by joshgentry** [comment]
Changed to "Generate Wallet / Login" for now until we want to rework the UI more broadly
